language: java
jdk:
  - oraclejdk8
env:
  global:
  - secure: HV81tYgIcC0sRQr4LU1tyyS/oXknRHr3f5ACe4Nbt6Po44g7HsonWQY2cupFiFdLjwbwQk3RFaw7N+gyEY2SLs3CtMJb1ro5cMjhRyu9l8zwUFDrkAwz/EXku0JvBMPYMVf5/h/Gjw+O8NyZwfuYqWD3y3634OGbgDPSGppaQ9nBdMkowX4BBz/OzUd+sSOnGGQLBJtcl5G6kLrRr+PDryeLX3DjLKc9Fc7/qd1uo486O+F7pdprY7q/3o7XuOas7GY80ZcAVf55vpbU/AaEcJhFKhLkSf+56vBPR5rc+lGFJdnbXUjsR0Tq2JWQBc8jR4+uEvurXCwY5imJTLN90JTHIB9y1v/PPtJTK9PMFwPzatcQeb/sB/LujjqUQezrMP6XmTgegOg/1jSDE9YxGz2snBgpmoQRyREu58MFZt998y0Ocgk8ISecmlo4uVkv2Gqr+Ckg5kLlwwmTYFIIIkOPZYIllrp0jSH05nBokA+FuQu+k0coT7sRKBAgO1cmIauh90YHIyYfRrFjP8UguTynogSEP0QSvUV0olkls6vytjN1fHf+X18eANCCThArXg9cv5wAVx3mmUjk31huU+fXpmP1oCzkIhdYOBWAKUFTmLABgTe6lW+ReiP7x9cwlhwrP0FOHuXkj18sVHIhij0DPpzM/ED8/sU5+9BRJMo=
  - secure: gJpnXWd5xerJflSrluhWIJui3HXTi134n+Jt5oQiGPPOrxhKHs6WKgJnWKs3SuuuHF58BhRkHhIG7vQ9Np3WLn7Yujp0BfrDgsKmZje330cJc7f5ejfFBQVVIdguB+LeXbRyqskYFKIqsDDqZegeTu2ghSDed1aKtEAhmBabRxvlwGO/4R+bkDH75SbjNMJhUKpse9xy7b4bvJiwwsF07g7ZzVP1+h6lz0bQzlMh6fQmNxWtG491Oyfii+F1FZtPkbiqpQUTFeJ5z5PT3WlpFdsKkCAd3tBjt1IGoZHNJ+xxa4717JP7NseY4uc8USXLyhKdNd0/awjjMAcpvLR8R7XTZR4F64F2gORwy3mZNVT5GNYY/EmPOivXGGvmr7d5u1rz8sIa2QEzP1q1Sk3N1wkOpL8n/jpaUv3JjBo+wyS87Nbb0iJP6eB7DyDS4U6J99Ily+ZB3HfqHom5i126iLz0DjhZDiIYPOGj/3NJaOIPMv81Z1ZPpN+au1IAzBw8zWn9ZvWBpggK13ZPEDJ7ivGAciRar2WZ2k7NdrR9RFHIkynja+i9SHwks3fiuZmqKndH4HyfVATZwFZLNYUJpNrBKuOACQV7TznYjE+PuvJGzho+1TiEaakedE6KbKNi9bLZQSE/SG2CxwlrFwoRLnLeXDxGxV/QDioVx2Y7fdo=
addons:
  sonarqube: true
  coverity_scan:
    project:
      name: chomnoue/QuickSearch
      description: Build submitted via Travis CI
    notification_email: chomnoue@yahoo.fr
    build_command_prepend: mvn clean
    build_command: mvn -DskipTests=true compile
    branch_pattern: coverity
before_install:
  - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.login=$SONAR_TOKEN
